# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KidsNote' do
    
pod 'MBProgressHUD'
pod 'Alamofire'
pod 'FFToolModule’
pod 'BYToolModule’
pod 'SwiftyUserDefaults'

    use_frameworks!

end
